spring:
  application:
    name: DeliveryFood
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery-food
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: HikariPool-DeliveryFood
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
          ddl_auto: validate
          show_sql: true
          open_in_view: false
          format_sql: true
          use_sql_comments: true
