spring:
  application:
    name: DeliveryFood
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery-food
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: HikariPool-DeliveryFood
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
          ddl_auto: validate
          show_sql: true
          open_in_view: false
          format_sql: true
          use_sql_comments: true
  cassandra:
    local-datacenter: datacenter1
    keyspace-name: delivery_food_keyspace
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    username: MykhailoK
    password: asdqeGtm2121q2
    port: 9042
    contact-points: localhost

